"""``onenexus-cas-client`` — typed async client for the Central Auth Service.

The ``CasClient`` facade is hand-written; the request/response models and
request builders under ``generated`` are produced by Microsoft Kiota from
``specs/cas/openapi.json``. Credential primitives live in ``onenexus-sdk-core``
and are adapted to Kiota's request adapter.
"""

from __future__ import annotations

from . import generated
from .client import (
    AcceptInvitationRequest,
    AcceptInvitationResponse,
    AddServiceClientKeyRequest,
    AddServiceClientKeyResponse,
    AssignRoleRequest,
    AssignRoleResponse,
    AssumeS3RoleRequest,
    AssumeS3RoleResponse,
    AttachPolicyToRoleRequest,
    AttachPolicyToRoleResponse,
    AuthorizationRelationshipRemovedResponse,
    CasClient,
    CreateAuthorizationRoleRequest,
    CreateAuthorizationRoleResponse,
    CreateServiceClientRequest,
    CreateServiceClientResponse,
    CreateUserRequest,
    CreateUserResponse,
    DeleteAuthorizationRoleRequest,
    DeleteAuthorizationRoleResponse,
    DeletePolicyRequest,
    DeletePolicyResponse,
    DetachPolicyFromRoleRequest,
    DisableServiceClientRequest,
    DisableServiceClientResponse,
    ListAuthorizationRolesRequest,
    ListAuthorizationRolesResponse,
    ListPolicyAttachmentsRequest,
    ListPolicyAttachmentsResponse,
    ListRoleAssignmentsRequest,
    ListRoleAssignmentsResponse,
    ListRolePoliciesRequest,
    ListS3RolesResponse,
    ListServiceClientsResponse,
    ListUsersRequest,
    ListUsersResponse,
    PublishPolicyRequest,
    PublishPolicyResponse,
    RemoveRoleAssignmentRequest,
    RemoveServiceClientKeyRequest,
    RemoveServiceClientKeyResponse,
    ResendUserInvitationRequest,
    UpdateAuthorizationRoleDescriptionRequest,
    UpdateAuthorizationRoleDescriptionResponse,
    UpdatePolicyRequest,
    UpdatePolicyResponse,
    UpdateProfileRequest,
    UpdateProfileResponse,
    resolve_assume_s3_role_base_url,
)

__all__ = [
    "AcceptInvitationRequest",
    "AcceptInvitationResponse",
    "AddServiceClientKeyRequest",
    "AddServiceClientKeyResponse",
    "AssignRoleRequest",
    "AssignRoleResponse",
    "AssumeS3RoleRequest",
    "AssumeS3RoleResponse",
    "resolve_assume_s3_role_base_url",
    "AttachPolicyToRoleRequest",
    "AttachPolicyToRoleResponse",
    "AuthorizationRelationshipRemovedResponse",
    "CasClient",
    "CreateAuthorizationRoleRequest",
    "CreateAuthorizationRoleResponse",
    "CreateServiceClientRequest",
    "CreateServiceClientResponse",
    "CreateUserRequest",
    "CreateUserResponse",
    "DeleteAuthorizationRoleRequest",
    "DeleteAuthorizationRoleResponse",
    "DeletePolicyRequest",
    "DeletePolicyResponse",
    "DisableServiceClientRequest",
    "DisableServiceClientResponse",

    "DetachPolicyFromRoleRequest", 

    "ListAuthorizationRolesRequest",
    "ListAuthorizationRolesResponse",

    "ListPolicyAttachmentsRequest",
    "ListPolicyAttachmentsResponse",
    "ListRoleAssignmentsRequest",
    "ListRoleAssignmentsResponse",
    "ListRolePoliciesRequest",
    "ListS3RolesResponse",
    "ListServiceClientsResponse",
    "ListUsersRequest",
    "ListUsersResponse",
    "PublishPolicyRequest",
    "PublishPolicyResponse",

    "RemoveRoleAssignmentRequest",
    "RemoveServiceClientKeyRequest",
    "RemoveServiceClientKeyResponse",
    "ResendUserInvitationRequest",
    "UpdateAuthorizationRoleDescriptionRequest",
    "UpdateAuthorizationRoleDescriptionResponse",
    "UpdatePolicyRequest",
    "UpdatePolicyResponse",
    "UpdateProfileRequest",
    "UpdateProfileResponse",

    "generated",
]
